### Gernelles
# venv aktivieren!
# cmd
# cd website-mkdocs
# .\venv\Scripts\activate.bat
# code .
site_url: https://html.thomaschewski.de/

### Mkdocs
# https://squidfunk.github.io/mkdocs-material/reference/ 

### Link zur mkdocs.yml
# https://github.com/squidfunk/mkdocs-material/blob/master/mkdocs.yml#L135C3-L138C1
# https://github.com/james-willett/mkdocs-material-youtube-tutorial/blob/main/mkdocs.yml  (aus dem Video)
# https://squidfunk.github.io/mkdocs-material/getting-started/

### Blogging-Plugin schon installiert
# https://liang2kl.github.io/mkdocs-blogging-plugin/ 
# https://github.com/liang2kl/mkdocs-blogging-plugin

### VG WORT
# https://www.selbstaendig-im-netz.de/einnahmequellen/vg-wort-meldung-deadline-infos-zu-den-zaehlpixeln-geschaetze-einnahmen/
# <img style="display:none;" src="https://vg(123).met.vgwort.de/na/eine-lange-Reihe-von-Buchstaben-und-Ziffern" width="1" height="1" alt="">


site_name: Jörg Thomaschewski - Internet-Grundlagen

nav:
  - Home: index.md
  - '1. Die Geschichte des Internets':
      - 'Übersicht': '1Internet/index.md'
  - '2. Linux': 
      - 'Übersicht': '2Linux/index.md'
      - '2.1 Die Geschichte von Linux': '2Linux/2.1_Die_Geschichte_von_Linux.md'
      - '2.2 Wichtige Linux-Konzepte': '2Linux/2.2_Wichtige_Linux-Konzepte.md'
      - '2.3 Erstes Login auf dem Linux-Server': '2Linux/2.3_Erstes_Login_auf_dem_Linux-Server.md'
      - '2.4 Erste Schritte im Dateisystem': '2Linux/2.4_Erste_Schritte_im_Dateisystem.md'
      - '2.5 Linux-Befehle': '2Linux/2.5_Linux_Befehle.md'
      - '2.5.1 Paketverwaltung': '2Linux/2.5.1_Paketverwaltung.md'
      - '2.5.2 Dateisystembefehle und Operatoren': '2Linux/2.5.2_Dateisystembefehle_und_Operatoren.md'
      - '2.5.3 Text- und Dateibearbeitung': '2Linux/2.5.3_Text-_und_Dateibearbeitung.md'
      - '2.5.4 Systemverwaltung': '2Linux/2.5.4_Systemverwaltung.md'
      - '2.5.5 Finden und Ersetzen': '2Linux/2.5.5_Finden_und_Ersetzen.md'
      - '2.5.6 Rechte ändern': '2Linux/2.5.6_Rechte_aendern.md'
      - '2.5.7 Systeminformationen': '2Linux/2.5.7_Systeminformationen.md'
      - '2.5.8 Prozessmanagement': '2Linux/2.5.8_Prozessmanagement.md'
      - '2.5.9 Archivierungs- und Komprimierungsbefehle': '2Linux/2.5.9_Archivierungs-_und_Komprimierungsbefehle.md'
      - '2.5.10 Netzwerkbefehle': '2Linux/2.5.10_Netzwerkbefehle.md'
      - '2.6 Bash': '2Linux/2.6_Bash.md'
      - '2.7 Dateisysteme und Linux': '2Linux/2.7_Dateisysteme_und_Linux.md'
      - '2.7.1 Dateisystem-Hierarchie und Struktur': '2Linux/2.7.1_Dateisystem-Hierarchie_und_Struktur.md'
      - '2.7.2 Wichtige Dateisysteme': '2Linux/2.7.2_Wichtige_Dateisysteme.md'
      - '2.7.3 Dateisystemoperationen': '2Linux/2.7.3_Dateisystemoperationen.md'
      - '2.7.4 Festplatten und ihre Lebensdauer': '2Linux/2.7.4_Festplatten_und_ihre_Lebensdauer.md'
      - '2.7.5 Festplattenverbund': '2Linux/2.7.5_Festplattenverbund.md'
      - '2.8 Selbsttest zu Linux': '2Linux/2.8_Selbsttest_zu_Linux.md'
  - '3. Mediennetzwerke': 
      - 'Übersicht': '3Netze/index.md'
      - 'Die Geschichte der Mediennetzwerke': '3Netze/3.1_Die Geschichte_der_Mediennetzwerke.md'
      - 'Beispiele warum Netzwerkwissen wichtig ist': '3Netze/3.2_Beispiele_warum_Netzwerkwissen_wichtig_ist.md'
      - 'Generelle Netzwerktopologien und Netzwerktypen': '3Netze/3.3_Generelle_Netzwerktopologien_und_Netzwerktypen.md'
      - 'ISO/OSI Schichtenmodell': '3Netze/3.4_ISO-OSI_Schichtenmodell.md'
      - 'Netzwerkprotokolle': '3Netze/3.5_Netzwerkprotokolle.md'
      - 'MAC und IP-Adressen': '3Netze/3.6_MAC_IP_Adressen.md'
      - 'Grundlegende Linux-Netzwerkbefehle': '3Netze/3.7_Grundlegende_Linux-Netzwerkbefehle.md'
      - 'Netzwerkhardware': '3Netze/3.8_Netzwerkhardware.md'
      - 'Netzwerksicherheit': '3Netze/3.9_Netzwerksicherheit.md'
      - 'Netzwerkmanagement': '3Netze/3.10_Netzwerkmanagement.md'
  - '4. HTML': 
      - 'Übersicht': '4Html/index.md'
      - '4.1 HTML-Grundlagen und Metadaten': '4Html/4.1_HTML_Grundlagen_und_Metadaten.md'
      - '4.1.1 Sinn und Zweck von HTML': '4Html/4.1.1_Sinn_und_Zweck_von_HTML.md'
      - '4.1.2 Entstehung von HTML und W3C': '4Html/4.1.2_Entstehung_von_HTML_und_W3C.md'
      - '4.1.3 Einführung in die HTML-Syntax': '4Html/4.1.3_Einfuehrung_in_die_HTML_Syntax.md'
      - '4.1.4 Elemente im HTML-Header': '4Html/4.1.4_Elemente_im_HTML_Header.md'
      - '4.1.5 Attribute zum Header-Element meta': '4Html/4.1.5_Attribute_zum_Header_Element_meta.md'
      - '4.1.6 Selbsttest zu HTML-Grundlagen und Metadaten': '4Html/4.1.6_Selbsttest_zu_HTML_Grundlagen_und_Metadaten.md'
      - '4.1.7 Wissen anwenden: HTML-Metadaten': '4Html/4.1.7_Wissen_anwenden_HTML_Metadaten.md'
      - '4.2 Ein HTML-Dokument erstellen': '4Html/4.2_Ein_HTML_Dokument_erstellen.md'
      - '4.2.1 HTML-Seitenstruktur': '4Html/4.2.1_HTML_Seitenstruktur.md'
      - '4.2.2 HTML-Seitenstruktur 2': '4Html/4.2.2_HTML_Seitenstruktur_2.md'
      - '4.2.3 HTML-Seitenstruktur im Überblick': '4Html/4.2.3_HTML_Seitenstruktur_im_Ueberblick.md'
      - '4.2.4 HTML-Struktur: Kommentare, Zeilenumbrüche und Absätze': '4Html/4.2.4_HTML_Struktur_Kommentare_Zeilenumbrueche_und_Absaetze.md'
      - '4.2.5 HTML-Struktur: Listen': '4Html/4.2.5_HTML_Struktur_Listen.md'
      - '4.2.6 HTML-Struktur: Elemente für Formatierungen': '4Html/4.2.6_HTML_Struktur_Elemente_fuer_Formatierungen.md'
      - '4.2.7 Links und Anker im HTML-Dokument': '4Html/4.2.7_Links_und_Anker_im_HTML_Dokument.md'
      - '4.2.8 Grafiken einbinden': '4Html/4.2.8_Grafiken_einbinden.md'
      - '4.2.9 Die Elemente figure und figcaption nutzen': '4Html/4.2.9_Die_Elemente_figure_und_figcaption_nutzen.md'
      - '4.2.10 SVG-Grafiken verwenden': '4Html/4.2.10_SVG_Grafiken_verwenden.md'
      - '4.2.11 Medien einbinden': '4Html/4.2.11_Medien_einbinden.md'
      - '4.2.12 Tabellen erstellen': '4Html/4.2.12_Tabellen_erstellen.md'
      - '4.2.13 Weitere HTML-Elemente': '4Html/4.2.13_Weitere_HTML_Elemente.md'
      - '4.2.14 Selbsttest zu HTML-Dokument erstellen': '4Html/4.2.14_Selbsttest_zu_HTML_Dokument_erstellen.md'
      - '4.3 HTML-Formulare': '4Html/4.3_HTML_Formulare.md'
      - '4.3.1 Formulare erstellen': '4Html/4.3.1_Formulare_form.md'
      - '4.3.2 Eingabefelder input': '4Html/4.3.2_Eingabefelder_input.md'
      - '4.3.3 Attribute für das input-Element': '4Html/4.3.3_Attribute_fuer_das_input_Element.md'
      - '4.3.4 Radio Buttons und Checkboxen': '4Html/4.3.4_Radio_Buttons_und_Checkboxen.md'
      - '4.3.5 Eingabebereiche textarea': '4Html/4.3.5_Eingabebereiche_textarea.md'
      - '4.3.6 Auswahllisten select': '4Html/4.3.6_Auswahllisten_select.md'
      - '4.3.7 Buttons und Absenden von Formularen': '4Html/4.3.7_Buttons_und_Absenden_von_Formularen.md'
      - '4.3.8 Selbsttest zu HTML-Formulare': '4Html/4.3.8_Selbsttest_zu_HTML_Formulare.md'
      - '4.4 HTML Hinweise und Tipps': '4Html/4.4_HTML_Hinweise_und_Tipps.md'
      - '4.4.1 Responsive Design und Mobile First': '4Html/4.4.1_Responsive_Design_Mobile_First.md'
      - '4.4.2 Konventionen über Dateinamen': '4Html/4.4.2_Konventionen_ueber_Dateinamen.md'
      - '4.4.3 Sonderzeichen und Umlaute': '4Html/4.4.3_Sonderzeichen_und_Umlaute.md'
      - '4.5 Zusammenfassung Kapitel HTML': '4Html/4.5_Zusammenfassung_Kapitel_HTML.md'
      - '4.5.1 Selbsttest zum gesamten Kapitel HTML': '4Html/4.5.1_Selbsttest_zum_gesamten_Kapitel_HTML.md'
      - '4.5.2 Aufgabe zum Kapitel HTML': '4Html/4.5.2_Aufgabe_zum_Kapitel_HTML.md'
  - '5. DOM': 
      - 'Übersicht': '5Dom/index.md'
      - '5.1 Einführung in das Document Object Model': '5Dom/5.1_Einfuehrung_in_das_Document_Object_Model.md'
      - '5.2 Grundlagen von DOM': '5Dom/5.2_Grundlagen_von_DOM.md'
      - '5.3 Navigieren im DOM-Baum': '5Dom/5.3_Navigieren_im_DOM_Baum.md'
      - '5.4 Anwendungsbeispiele': '5Dom/5.4_Anwendungsbeispiele.md'
      - '5.5 Selbsttest zum gesamten Kapitel DOM': '5Dom/5.5_Selbsttest_und_Zusammenfassung_zum_gesamten_Kapitel_DOM.md'
  - '6. CSS':     
      - 'Übersicht': '6Css/index.md'
      - '6.1 Einführung in Cascading Style Sheets (CSS)': '6Css/6.1_Einfuehrung_in_Cascading_Style_Sheets.md' 
      - '6.2 Grundlagen der CSS-Formatierung': '6Css/6.2_Grundlagen_der_CSS_Formatierung.md'
      - '6.2.1 CSS-Syntax und Befehle definieren': '6Css/6.2.1_CSS_Syntax_Befehle_definieren.md'
      - '6.2.2 CSS in HTML einbinden – Möglichkeiten': '6Css/6.2.2_CSS_in_HTML_einbinden_Moeglichkeiten.md'
      - '6.2.3 Fazit: CSS in HTML einbinden': '6Css/6.2.3_CSS_in_HTML_einbinden_Fazit.md'
      - '6.2.4 Kommentare im Stylesheet': '6Css/6.2.4_Kommentare_im_Stylesheet.md'
      - '6.2.5 CSS-Formate auf HTML-Elemente anwenden': '6Css/6.2.5_CSS_Formate_auf_HTML_Elemente_anwenden.md'
      - '6.2.6 Gruppierung': '6Css/6.2.6_Gruppierung.md'
      - '6.2.7 Verschachtelung': '6Css/6.2.7_Verschachtelung.md'
      - '6.2.8 Sammeleigenschaften': '6Css/6.2.8_Sammeleigenschaften.md'
      - '6.2.9 Die Elemente `div` und `span`': '6Css/6.2.9_Die_Elemente_div_und_span.md'
      - '6.2.10 Klassenselektoren': '6Css/6.2.10_Klassenselektoren.md'
      - '6.2.11 ID-Selektoren – Individualformate definieren': '6Css/6.2.11_ID_Selektoren_Individualformate_definieren.md'
      - '6.2.12 Der Unterschied zwischen Klassen und IDs': '6Css/6.2.12_Der_Unterschied_zwischen_Klassen_und_IDs.md'
      - '6.2.13 Pseudoklassen': '6Css/6.2.13_Pseudoklassen.md'
      - '6.2.14 Selektoren und Spezifität': '6Css/6.2.14_Selektoren_und_Spezifitaet.md'
      - '6.2.15 Exkurs: Eigenschaftswerte, Längenmaße, Farben, Schlüsselwörter': '6Css/6.2.15_Exkurs_Eigenschaftswerte_Laengenmasse_Farben_Schluesselwoerter.md'
      - '6.2.16 Selbsttest zu Grundlagen der CSS-Formatierung': '6Css/6.2.16_Selbsttest_zu_Grundlagen_der_CSS_Formatierung.md'
      - '6.3 Erweiterung der CSS-Formatierung': '6Css/6.3_Erweiterung_der_CSS_Formatierung.md'
      - '6.3.1 Hintergrundformatierung': '6Css/6.3.1_Hintergrundformatierung.md'
      - '6.3.2 Schriftformatierung': '6Css/6.3.2_Schriftformatierung.md'
      - '6.3.3 Absätze und Ausrichtungen': '6Css/6.3.3_Absaetze_und_Ausrichtungen.md'
      - '6.3.4 Listenformatierung': '6Css/6.3.4_Listenformatierung.md'
      - '6.3.5 Selbsttest zu Erweiterung der CSS-Formatierung': '6Css/6.3.5_Selbsttest_zu_Erweiterung_der_CSS_Formatierung.md'
      - '6.4 Positionieren von CSS-Elementen': '6Css/6.4_Positionieren_von_CSS_Elementen.md'
      - '6.4.1 Größe von Elementen': '6Css/6.4.1_Groesse_von_Elementen.md'
      - '6.4.2 Positionierung von Elementen': '6Css/6.4.2_Positionierung_von_Elementen.md'
      - '6.4.3 Anzeigeoptionen für Elemente': '6Css/6.4.3_Anzeigeoptionen_fuer_Elemente.md'
      - '6.4.4 Rahmengestaltung': '6Css/6.4.4_Rahmengestaltung.md'
      - '6.4.5 Außenabstand (`margin`)': '6Css/6.4.5_Aussenabstand_margin.md'
      - '6.4.6 Innenabstand (`padding`)': '6Css/6.4.6_Innenabstand.md'
      - '6.4.7 Formulare formatieren': '6Css/6.4.7_Formulare_formatieren.md'
      - '6.4.8 Das Box-Modell': '6Css/6.4.8_Das_Box_Modell.md'
      - '6.4.9 CSS Float': '6Css/6.4.9_CSS_Float.md'
      - '6.4.10 CSS Flexbox – Basiskonzept': '6Css/6.4.10_CSS_Flexbox_Basiskonzept.md'
      - '6.4.11 CSS Flexbox – Verteilung auf Hauptachse und Querachse': '6Css/6.4.11_CSS_Flexbox_Verteilung_auf_Hauptachse.md'
      - '6.4.12 CSS Multiline Flexbox': '6Css/6.4.12_CSS_Multiline_Flexbox.md'
      - '6.4.13 Selbsttest zu Positionieren von CSS-Elementen': '6Css/6.4.13_Selbsttest_zu_Positionieren_von_CSS_Elementen.md'
      - '6.5 CSS-Tipps': '6Css/6.5_CSS_Tipps.md'
      - '6.5.1 Normalize.css': '6Css/6.5.1_Normalize.css.md'
      - '6.5.2 Strukturierter Aufbau einer CSS-Datei': '6Css/6.5.2_Strukturierter_Aufbau_einer_CSS_Datei.md'
      - '6.5.3 SCSS, Sass und Less': '6Css/6.5.3_SCSS_Sass_Less.md'
      - 'Selbsttest, Aufgabe und Zusammenfassung zum Kapitel CSS': '6Css/6.6_Selbsttest_Aufgabe_und_Zusammenfassung_zum_Kapitel_CSS.md'
  - '7. JavaScript': 
      - 'Übersicht': '7JavaScript/index.md'

theme:
  name: material
  # name: material <- aus dem Video
  # name: readthedocs <- NEIN. Lizenz kostet Geld
  # name: windmill <- NEIN. wenig Konfigurationsmöglichkeiten
  # ansehen sphinx https://www.sphinx-doc.org/en/master/usage/quickstart.html 
  # https://github.com/mkdocs/mkdocs/wiki/MkDocs-Themes
  
  
  #logo: assets/jt.jpg       # Bindet kleines Logo oben links ein
  #favicon: favicon.ico
  
  custom_dir: overrides     # https://squidfunk.github.io/mkdocs-material/customization/#extending-the-theme

  font: false                 # Keine Google-Fonts laden

  #font:                     
  #  text: Roboto             # https://fonts.google.com/

  features:
  # https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/
  #  - navigation.tabs         # Nav oben
  #  - navigation.tabs.sticky  # Nav oben bleibt auch beim scrollen
  #  - navigation.sections     # blendet links alle sections mit ein
    - navigation.footer        # gibt einen Zurück-Button im Footer
    - navigation.tracking      # linke Nav läuft beim Scrollen automatisch mit
    - -navigation.expand       # Nav links ausgeklappt
    - navigation.indexes       # Keine doppelte Überschriften direkt untereinander
  #  - navigation.top          # Pfeil nach oben wird angezeigt
    - toc.integrate            # Ohne Navi auf der rechten Seite
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation  # Code kann einen Kommentar enthalten https://squidfunk.github.io/mkdocs-material/reference/code-blocks/#adding-annotations
    - content.code.copy        # Erstellt einen Button um Code zu kopieren
    - content.tooltips
  language: de
    
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Zum Dark-mode
      primary: indigo   # Hauptfarbe: https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/#primary-color
      accent: red 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Zum Light-mode    
      primary: indigo
      accent: red

#  icon:
#    admonition:
#      question: octicons/question-16 

plugins:
  - social
  - search
  - open-in-new-tab           # Alle Links in externen Tabs öffnen
#  - ezlinks:
#      wikilinks: true         # Erlaubt Wikilinks in [[  ]] - ist aber veraltet und wird abgeschaltet
#  - mermaid2                  # Grafische Darstellung von UML-Diagrammen
#  - blog:
#      blog_dir: .
#      post_readtime: false
      # base_path: blog
      # show_recent: 5
      # date_format: '%Y-%m-%d'
      #tags:
      #  - Tech
      #  - MkDocs
      #  - Blogging
  #- git-revision-date-localized:
  #    type: 'datetime'
  #    locale: 'de'


extra_css:     # https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#content-area-width 
  - stylesheets/extra.css

extra_javascript:
    - https://unpkg.com/mermaid/dist/mermaid.min.js
    - js/custom.js

extra:
  social:
    - icon: fontawesome/brands/google
      link: https://scholar.google.de/citations?user=-Oj8JzgAAAAJ
    - icon: fontawesome/brands/researchgate
      link: https://www.researchgate.net/profile/Joerg_Thomaschewski
    - icon: fontawesome/brands/linkedin
      link: https://de.linkedin.com/in/j%C3%B6rg-thomaschewski-7074786/de
    - icon: fontawesome/brands/xing
      link: https://www.xing.com/profile/Joerg_Thomaschewski
    - icon: fontawesome/solid/envelope
      link: mailto:joerg.thomaschewski@hs-emden-leer.de 

markdown_extensions:
  - abbr
  - attr_list  
  - md_in_html
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - footnotes
  - toc:
      toc_depth: 0                # hierdurch werden keine Unterstrukturen TOC einer Seite angezeigt
  - admonition                    # hierdurch können Bereiche ein- und ausgeklappt werden
  - pymdownx.details              # hierdurch können Bereiche ein- und ausgeklappt werden
  - pymdownx.superfences          # hierdurch können Bereiche ein- und ausgeklappt werden
  - pymdownx.mark
  - pymdownx.arithmatex:
      generic: true 
  - pymdownx.highlight:
      anchor_linenums: true 
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.superfences:
        # make exceptions to highlighting of code:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid_custom

copyright: |
  &copy; 2023-2024 für alle Inhalte Jörg Thomaschewski --- <a href="https://thomaschewski.de/Weitere/Impressum/">Impressum</a> --- <a href="https://thomaschewski.de/Weitere/Datenschutzerklaerung/">Datenschutzerklärung</a> 